In [26]:
import numpy as np
import math
import time

In [27]:
data_path = "/content/drive/MyDrive/adventofcode/2021/data_11.txt"

def parse_file(data_path):
    with open(data_path) as f:
        #lines = [int(number) for line in f.read().splitlines() for number in line]
        lines = np.array([[int(number) for number in line] for line in f.read().splitlines()])
    return lines

data = parse_file(data_path)
print(data.shape)
print(data)

(10, 10)
[[1 2 5 4 1 1 7 2 2 8]
 [4 4 1 6 8 7 3 2 2 4]
 [8 3 5 4 3 8 1 5 5 3]
 [1 3 7 2 6 3 7 6 1 4]
 [5 5 8 6 5 3 8 5 5 3]
 [7 2 1 3 3 3 3 4 2 7]
 [3 5 7 1 3 6 2 8 2 5]
 [1 6 8 1 1 2 6 2 4 3]
 [8 7 1 8 3 1 2 1 3 8]
 [5 2 5 4 2 6 6 3 4 7]]


In [28]:
def neighborhood(index, matrix):
    num_neighbor = 1
    top = max(0,index[0]-num_neighbor)
    bottom = max(0,index[0]+num_neighbor+1)
    left = max(0,index[1]-num_neighbor)
    right = max(0,index[1]+num_neighbor+1)
    n_slice_indexes = [top, bottom, left, right]
    return n_slice_indexes

In [29]:
def flashes(octos, steps):
    flash_counter = 0
    sync_flash_step = -1
    step_counter = 0
    while sync_flash_step == -1 or step_counter <= steps: 
        step_counter += 1
        octos +=1
        while np.any(octos >= 10):
            indexes = np.where(octos >= 10)
            octos[indexes] = 0
            row_i, col_i = indexes
            if step_counter <= steps:
                flash_counter += len(row_i)
            for i in range(len(row_i)):
                flash_index = (row_i[i], col_i[i])
                nh_slices = neighborhood(flash_index, octos)
                r_start, r_stop, c_start, c_stop = nh_slices
                octos[r_start:r_stop, c_start:c_stop][octos[r_start:r_stop, c_start:c_stop] != 0] += 1
        if np.all(octos==0) and sync_flash_step == -1:
            sync_flash_step = step_counter
        
    return flash_counter, sync_flash_step

start_time = time.time()
octos = data.copy()
steps = 100
flash_counter, sync_flash_step = flashes(octos, steps) 
print("Answer part 1 --> number of flashes after {} steps: {}".format(steps,flash_counter)) 
print("answer part 2 --> all octos flash simultaneously at step: " , sync_flash_step)
print("--- %s milliseconds ---" % ((time.time() - start_time)*1000))

Answer part 1 --> number of flashes after 100 steps: 1773
answer part 2 --> all octos flash simultaneously at step:  494
--- 129.56857681274414 milliseconds ---
