In [21]:
import numpy as np

In [22]:
data_path = "/content/drive/MyDrive/adventofcode/2021/data_3.txt"
with open(data_path) as f:
    report = np.array([[int(char) for char in word.strip()] for word in f.read().splitlines()])
print(report)

[[0 1 1 ... 1 0 1]
 [0 1 1 ... 1 1 1]
 [0 0 0 ... 1 0 1]
 ...
 [0 1 0 ... 1 0 1]
 [0 1 0 ... 0 0 0]
 [1 0 0 ... 1 0 0]]


In [23]:
#part 1
def get_power_consumption(diagnostic):
    most_common_bits = []
    least_common_bits = []
    for i in range(len(diagnostic[0])):
        elm_count = np.bincount(diagnostic[:,i])
        most_common_bits.append(elm_count.argmax())
        least_common_bits.append(elm_count.argmin())
    gamma = int("".join(str(x) for x in most_common_bits), 2)
    epsilon = int("".join(str(x) for x in least_common_bits), 2)
    power_consumption = gamma*epsilon
    return power_consumption

print("Answer part 1 -- power consumption: ", get_power_consumption(report))

Answer part 1 -- power consumption:  4174964


In [24]:
#part 2
def get_rating(leftovers, index=0, oxy=True):
    if len(leftovers) == 1:
        rating = int("".join(str(x) for x in leftovers[0].tolist()), 2)
        return rating
    else:
        elm_count = np.bincount(leftovers[:,index])
        if np.unique(elm_count).size==1:
            if oxy == True:
                most_common_bit = 1
            else:
                most_common_bit = 0
        else:
            if oxy == True:
                most_common_bit = elm_count.argmax()
            else:
                most_common_bit = elm_count.argmin()
        leftovers = leftovers[leftovers[:,index]==most_common_bit] 
        return(get_rating(leftovers, index=index+1, oxy=oxy))
        

oxy_generator_rating = get_rating(report)
print("oxy_generator_rating: ", oxy_generator_rating)
co2_scrubber_rating = get_rating(report,oxy=False)
print("co2_scrubber_rating: ", co2_scrubber_rating)
print("Answer part 2 -- life_support_rating: ", oxy_generator_rating*co2_scrubber_rating)

oxy_generator_rating:  1371
co2_scrubber_rating:  3264
Answer part 2 -- life_support_rating:  4474944
