In [245]:
import numpy as np
import re

In [246]:
data_path = "/content/drive/MyDrive/adventofcode/2021/data_4.txt"
with open(data_path) as f:
    lines = [word for word in f.read().splitlines() if word]
print(len(lines))

501


In [247]:
moves = np.array([int(word) for word in re.split(",", lines[0])])
print("#moves: ", len(moves))
print("moves: ", moves) 

#moves:  100
moves:  [13 47 64 52 60 69 80 85 57  1  2  6 30 81 86 40 27 26 97 77 70 92 43 94
  8 78  3 88 93 17 55 49 32 59 51 28 33 41 83 67 11 91 53 36 96  7 34 79
 98 72 39 56 31 75 82 62 99 66 29 58  9 50 54 12 45 68  4 46 38 21 24 18
 44 48 16 61 19  0 90 35 65 37 73 20 22 89 42 23 15 87 74 10 71 25 14 76
 84  5 63 95]


In [248]:
boards = np.array([[int(number) for number in word.split()] for word in lines[1:]])
desired_shape = (int(len(boards)/(len(boards[0]))), len(boards[0]),len(boards[0]))
boards = np.array(boards).reshape(desired_shape)
print("Shape of boards: ", boards.shape)
print("Min number: ", boards.min())
print("Max number: ", boards.max())
print("First three boards: \n", boards[:3])

Shape of boards:  (100, 5, 5)
Min number:  0
Max number:  99
First three boards: 
 [[[88 67 20 19 15]
  [22 76 86 44 73]
  [ 7 42  6 69 25]
  [12 68 92 21 75]
  [97 45 13 52 70]]

 [[75 98 24 18 77]
  [17 93 46 49 13]
  [92 56 97 57 66]
  [44  0 65 54 74]
  [23  6 53 42 20]]

 [[92 94  9 27 41]
  [73 28 62 90 40]
  [78  3 12 37 32]
  [ 8 86 91 16 30]
  [84 38 68 11 19]]]


In [249]:
def first_winner_score(moves, boards):
    mark = -1
    target = mark * len(boards[0])
    boards = boards.copy() #avoid value changes to persist outside fn 
    for move in moves:
        boards[boards==move]= mark
        for board in boards:
            sums = np.append(board.sum(axis=0), board.sum(axis=1)) #all column and row sums
            if target in sums:
                final_sum = (np.where(board>-1,board,0)).sum() #all neg vals changed to zero, all summed
                return final_sum*move

print("Answer part 1 -- first winner final score: ", first_winner_score(moves, boards))

Answer part 1 -- first winner final score:  49686


In [250]:
def last_winner_score(moves, boards):
    mark = -1
    target = mark * len(boards[0])
    boards = boards.copy() #avoid value changes to persist outside fn
    for move in moves:
        boards[boards==move]= mark
        winner_inds = []
        for i, board in enumerate(boards):
            sums = np.append(board.sum(axis=0), board.sum(axis=1)) #all column and row sums   
            if target in sums :
                winner_inds.append(i)
                if len(boards) == 1:
                    final_sum = (np.where(boards[0]>-1,boards[0],0)).sum() #all neg vals changed to zero, all vals summed
                    return final_sum*move
        boards = np.delete(boards,winner_inds, axis=0)
        
print("Answer part 2 -- last winner final score: ", last_winner_score(moves, boards))

Answer part 2 -- last winner final score:  26878


In [251]:
#alternative idea/nice general approach as seen on reddit:
#calculate list of winners in the order they won

def calculate_winners(moves, boards):
    winners = []
    mark = -1
    target = mark * len(boards[0])
    boards = boards.copy() #avoid value changes to persist outside fn
    for move in moves:
        boards[boards==move]= mark
        winner_inds = []
        for i, board in enumerate(boards):
            sums = np.append(board.sum(axis=0), board.sum(axis=1)) #all column and row sums   
            if target in sums :
                winner_inds.append(i)
                winners.append([board, move])
        boards = np.delete(boards,winner_inds, axis=0)
    return winners

winners = calculate_winners(moves, boards)
first_winner = winners[0]
last_winner = winners[-1]
print("Answer part 1 -- first winner final score: ",(np.where(first_winner[0]>-1,first_winner[0],0)).sum()*first_winner[1])
print("Answer part 2 -- last winner final score: ",(np.where(last_winner[0]>-1,last_winner[0],0)).sum()*last_winner[1])

Answer part 1 -- first winner final score:  49686
Answer part 2 -- last winner final score:  26878
