In [22]:
import numpy as np
import re

In [23]:
data_path = "/content/drive/MyDrive/adventofcode/2021/data_5.txt"
with open(data_path) as f:
    lines = f.read().splitlines()

vent_lines = np.array([[int(y) for y in (re.sub(",|\s->\s", " ",line)).split()] for line in lines])

print("#of vent lines: ", len(vent_lines))
print("First 5 vent lines:\n", vent_lines[:5])
print("Max value: ", vent_lines.max())
print("Min value: ", vent_lines.min())

#of vent lines:  500
First 5 vent lines:
 [[561 579 965 175]
 [735  73 316  73]
 [981 566 981  11]
 [631 588 631 910]
 [919 964  70 115]]
Max value:  989
Min value:  10


In [24]:
def overlaps(vent_lines, diagonal=False):
    vent_map = np.zeros((vent_lines.max()+1,vent_lines.max()+1))
    for vent in vent_lines:
        x1,y1,x2,y2 = vent
        y_start, y_stop = sorted((y1,y2))
        x_start, x_stop = sorted((x1,x2))
        if x1 == x2:
            vent_map[y_start:y_stop+1, x1] +=1
        elif y1==y2:
            vent_map[y1, x_start:x_stop+1] += 1
        elif diagonal==True:
            dim_size = x_stop - x_start + 1
            di = np.diag_indices(dim_size)
            if (x1 > x2 and y1 < y2) or (x1 < x2 and y1 > y2):  #if anti diagonal
                di = (di[0][::-1], di[1])
            vent_map[y_start:y_stop+1,x_start:x_stop+1][di] += 1
        
    return (np.count_nonzero(vent_map >= 2))


import time
start_time = time.time()


print("Answer part 1 -- #overlapping horizontal and vertical lines: ", overlaps(vent_lines))
print("Answer part 2 -- #overlapping horizontal, vertical, and diagonal lines: ",overlaps(vent_lines, diagonal=True))
print("--- %s milliseconds ---" % ((time.time() - start_time)*1000))

Answer part 1 -- #overlapping horizontal and vertical lines:  6005
Answer part 2 -- #overlapping horizontal, vertical, and diagonal lines:  23864
--- 15.237808227539062 milliseconds ---
